FROM scratch as rootfs
ARG RELEASE
LABEL org.opencontainers.image.ref.name="ubuntu"
LABEL org.opencontainers.image.version=$RELEASE
LABEL org.opencontainers.image.url=https://github.com/riscv-builders/task-images
LABEL org.opencontainers.image.source https://github.com/riscv-builders/task-images
LABEL org.opencontainers.image.authors=riscv-builders
LABEL org.opencontainers.image.licenses=BSD-3-Clause
LABEL org.opencontainers.image.description="Default image for riscv-builders"
ADD ubuntu-$RELEASE-oci-riscv64-root.tar.gz /

FROM rootfs as ubuntu-base
ARG RELEASE
COPY ubuntu.sources /etc/apt/sources.list.d/ubuntu.sources
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RUN apt-get update -yq
RUN apt-get upgrade -yq
RUN apt-get install ca-certificates curl sudo -yq --no-install-recommends
RUN apt-get install git git-lfs -yq --no-install-recommends
RUN apt-get install build-essential pkg-config -yq
RUN apt-get install cmake ninja-build -yq --no-install-recommends
RUN apt-get install llvm llvm-dev llvm-runtime -yq --no-install-recommends
RUN apt-get install python3 python3-dev python3-virtualenv pipx python3-poetry -yq --no-install-recommends
RUN apt-get install nodejs npm -yq --no-install-recommends
RUN apt-get install golang -yq --no-install-recommends
RUN apt-get install rustc cargo -yq --no-install-recommends
RUN apt-get install ghc cabal-install -yq --no-install-recommends
RUN apt-get install php -yq --no-install-recommends
RUN apt-get install openjdk-17-jre openjdk-17-jdk -yq --no-install-recommends

RUN apt-get clean
